article_dev_homepage:
    pattern:  /sous_category={id}
    defaults: { _controller: ArticleDevBundle:ArticleDev:index }
    
article_dev_article:
    pattern:  /s_{idSc}/article={idAr}
    defaults: { _controller: ArticleDevBundle:ArticleDev:showTheArticle }
    
article_dev_addCategory:
    pattern:  /addCategory
    defaults: { _controller: ArticleDevBundle:ArticleDev:addCategory }
