article_dev_homepage:
    pattern:  /
    defaults: { _controller: ArticleDevBundle:ArticleDev:index}
    
article_dev_show:
    pattern:  /sc={id}
    defaults: { _controller: ArticleDevBundle:ArticleDev:show }
    
article_dev_article:
    pattern:  /sc={idSc}/ar={idAr}
    defaults: { _controller: ArticleDevBundle:ArticleDev:showTheArticle }
    
article_dev_admin:
    pattern:  /admin
    defaults: { _controller: ArticleDevBundle:ArticleDev:admin }
    
article_dev_guideAdmin:
    pattern:  /admin/guideAdmin
    defaults: { _controller: ArticleDevBundle:ArticleDev:guideAdmin }
    
article_dev_addArticle:
    pattern:  /admin/addArticle
    defaults: { _controller: ArticleDevBundle:ArticleDev:addArticle }

article_dev_editArticle:
    pattern:  /admin/editArticle/ar={id}
    defaults: { _controller: ArticleDevBundle:ArticleDev:editArticle }

article_dev_delArticle:
    pattern:  /admin/delArticle/ar={id}
    defaults: { _controller: ArticleDevBundle:ArticleDev:delArticle }

article_dev_addCategory:
    pattern:  /admin/addCategory
    defaults: { _controller: ArticleDevBundle:CategoryDev:addCategory }

article_dev_showCategories:
    pattern:  /admin/allCategories
    defaults: { _controller: ArticleDevBundle:CategoryDev:showCategories }

article_dev_editCategory:
    pattern:  /admin/modifCategory={id}
    defaults: { _controller: ArticleDevBundle:CategoryDev:editCategory }

article_dev_delCategory:
    pattern:  /admin/delCategory={id}
    defaults: { _controller: ArticleDevBundle:CategoryDev:delCategory }

article_dev_addSubCategory:
    pattern:  /admin/addSubCategory
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:addSubCategory }

article_dev_editSubCategory:
    pattern:  /admin/editSubCategory={id}
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:editSubCategory }

article_dev_delSubCategory:
    pattern:  /admin/delSubCategory={id}
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:delSubCategory }

article_dev_addQuestion:
    pattern:  /admin/addQuestion
    defaults: { _controller: ArticleDevBundle:QuestionDev:addQuestion }

article_dev_editQuestion:
    pattern:  /admin/editQuestion={id}
    defaults: { _controller: ArticleDevBundle:QuestionDev:editQuestion }

article_dev_delQuestion:
    pattern:  /admin/delQuestion={id}
    defaults: { _controller: ArticleDevBundle:QuestionDev:delQuestion }

article_dev_addProposal:
    pattern:  /admin/addProposal
    defaults: { _controller: ArticleDevBundle:ProposalDev:addProposal }

article_dev_editProposal:
    pattern:  /admin/editProposal={id}
    defaults: { _controller: ArticleDevBundle:ProposalDev:editProposal }

article_dev_delProposal:
    pattern:  /admin/delProposal={id}
    defaults: { _controller: ArticleDevBundle:ProposalDev:delProposal }

article_dev_question:
    pattern:  /sc={idSC}/q={idQ}
    defaults: { _controller: ArticleDevBundle:ArticleDev:question }

article_dev_response:
    pattern:  /response
    defaults: { _controller: ArticleDevBundle:ProposalDev:check }
