article_dev_homepage:
    pattern:  /
    defaults: { _controller: ArticleDevBundle:ArticleDev:index}
    
article_dev_show:
    pattern:  /sc={id}
    defaults: { _controller: ArticleDevBundle:ArticleDev:show }
    
article_dev_article:
    pattern:  /sc={idSc}/ar={idAr}
    defaults: { _controller: ArticleDevBundle:ArticleDev:showTheArticle }
    
article_dev_admin:
    pattern:  /admin
    defaults: { _controller: ArticleDevBundle:ArticleDev:admin }
    
article_dev_guideAdmin:
    pattern:  /admin/guideAdmin
    defaults: { _controller: ArticleDevBundle:ArticleDev:guideAdmin }
    
article_dev_addArticle:
    pattern:  /admin/addArticle
    defaults: { _controller: ArticleDevBundle:ArticleDev:addArticle }

article_dev_editArticle:
    pattern:  /admin/editArticle
    defaults: { _controller: ArticleDevBundle:ArticleDev:editArticle }

article_dev_delArticle:
    pattern:  /admin/delArticle
    defaults: { _controller: ArticleDevBundle:ArticleDev:delArticle }

article_dev_addCategory:
    pattern:  /admin/addCategory
    defaults: { _controller: ArticleDevBundle:CategoryDev:addCategory }

article_dev_editCategory:
    pattern:  /admin/modifCategory
    defaults: { _controller: ArticleDevBundle:CategoryDev:editCategory }

article_dev_delCategory:
    pattern:  /admin/delCategory
    defaults: { _controller: ArticleDevBundle:CategoryDev:delCategory }

article_dev_addSubCategory:
    pattern:  /admin/addSubCategory
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:addSubCategory }

article_dev_editSubCategory:
    pattern:  /admin/modifSubCategory
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:editSubCategory }

article_dev_delSubCategory:
    pattern:  /admin/delSubCategory
    defaults: { _controller: ArticleDevBundle:SubCategoryDev:delSubCategory }
