<?php

namespace UTBM\ArticleDevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     *  Récupère les articles appartenant au sous menus qu'on a sélectionné
     */
    public function getArticlesAccueil($id){
        $query = $this->createQueryBuilder('ar')
                      ->leftJoin('ar.subCategory', 'sc') // les sous menus des menus
                        ->addSelect('sc')
                      ->where("sc.id = :id")
                      ->setParameter('id', $id)
                      ->getQuery();
        return $query->getResult();
    }
}
