<?php

namespace UTBM\ArticleDevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LMenuRepository extends EntityRepository
{
     /**
     *  Récupère les articles appartenant au sous menus qu'on a sélectionné
     */
    public function getLeftMenu(){
        $query = $this->createQueryBuilder('LM')
                      ->leftJoin('LM.lMenuElts', 'me')
                        ->addSelect('me')
                      ->getQuery();
        return $query->getResult();
    }
}
