<?php

namespace UTBM\ArticleDevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LMenuEltRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LMenuEltRepository extends EntityRepository
{
}
