<?php

namespace UTBM\ArticleDevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    /**
     *  Récupère les questions ainsi que les propositon de réponses appartenant au sous menus courrant
     */
    public function getQuestions($idSC){
        
        $query = $this->createQueryBuilder('q')
                      ->leftJoin('q.subCategory', 'sc')
                        ->addSelect('sc')
                      ->where("sc.id = :id")
                      ->setMaxResults(3)
                      ->setParameter('id', $idSC)
                      ->getQuery();
        return $query->getResult();
    }
}
