<?php

namespace UTBM\ArticleDevBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CategoryDevController__JMSInjector
{
    public static function inject($container) {
        $instance = new \UTBM\ArticleDevBundle\Controller\CategoryDevController();
        return $instance;
    }
}
