<?php

namespace Proxies\__CG__\UTBM\ArticleDevBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Question extends \UTBM\ArticleDevBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEntitled($entitled)
    {
        $this->__load();
        return parent::setEntitled($entitled);
    }

    public function getEntitled()
    {
        $this->__load();
        return parent::getEntitled();
    }

    public function setSubCategory(\UTBM\ArticleDevBundle\Entity\SubCategory $subCategory)
    {
        $this->__load();
        return parent::setSubCategory($subCategory);
    }

    public function getSubCategory()
    {
        $this->__load();
        return parent::getSubCategory();
    }

    public function addProposal(\UTBM\ArticleDevBundle\Entity\Proposal $proposals)
    {
        $this->__load();
        return parent::addProposal($proposals);
    }

    public function removeProposal(\UTBM\ArticleDevBundle\Entity\Proposal $proposals)
    {
        $this->__load();
        return parent::removeProposal($proposals);
    }

    public function getProposals()
    {
        $this->__load();
        return parent::getProposals();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'entitled', 'subCategory', 'proposals');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}